import type { DeathCause } from '../types';

// LEGACY M2.1: 以下の死因は M2.1 Step 3 で発火停止予定。
//   - ondo / taiko_crush / taiko_tobikomi（くそざこ音頭・太鼓やぐら廃止）
//   - cocoon_abuse（ココン廃止）
//   - suzu_kazoe_shikujiri（スズ廃止）
// テンプレートは図鑑 (dex) のため残す。新規発火は止める。
// 詳細: docs/M2-DIRECTION-RESET.md / docs/M2-MIGRATION-PLAN.md / docs/DIALOGUE-CATALOG.md
export const DEATH_CAUSES: Record<string, DeathCause> = {
  bokaigi: {
    id: 'bokaigi',
    title: '棒会議で極刑',
    rare: false,
    points: 12,
    template: (n) => `${n}は議題がわからないまま棒で殴られ続け倒れた。`,
  },
  ondo: {
    id: 'ondo',
    title: 'ふらつき転倒',
    rare: false,
    points: 8,
    template: (n) => `${n}は足元を確認しないまま小走りし、前の個体に引っかかって転倒した。`,
  },
  mudriver: {
    id: 'mudriver',
    title: '泥川溺水',
    rare: false,
    points: 6,
    template: (n) => `${n}は泥川の光る何かに吸い寄せられ、静かに沈んだ。`,
  },
  stonebread: {
    id: 'stonebread',
    title: '硬い木の実で歯折れ',
    rare: false,
    points: 7,
    template: (n) => `${n}は硬い木の実に噛みつき、歯と意識を同時に失った。`,
  },
  bridge: {
    id: 'bridge',
    title: '海辺で波にさらわれた',
    rare: false,
    points: 9,
    template: (n) => `${n}は海辺で水平線を眺めていたら、想定外の大波に足をすくわれてそのまま遠くへ流された。`,
  },
  fire: {
    id: 'fire',
    title: '火事に巻き込まれた',
    rare: false,
    points: 10,
    template: (n) => `${n}は煙の方へ様子を見に行き、そのまま火の中で迷子になった。`,
  },
  roushuai: {
    id: 'roushuai',
    title: '老衰（くそざこ寿命）',
    rare: false,
    points: 4,
    template: (n) => `${n}はまもりんを握りしめ、わふっと呟いて息絶えた。`,
  },
  philosophy: {
    id: 'philosophy',
    title: 'なぜわふ…で干からび',
    rare: true,
    points: 25,
    template: (n) => `${n}は「なぜわふ…」と立ち止まり、そのまま三日干からびた。`,
  },
  summer_boil: {
    id: 'summer_boil',
    title: '夏／沸騰池で煮え',
    rare: false,
    points: 14,
    template: (n) => `${n}は温泉と勘違いして沸騰寸前の泥水池に入り、そのまま出汁になった。`,
  },
  winter_snow: {
    id: 'winter_snow',
    title: '冬／雪を食べてそのまま',
    rare: false,
    points: 11,
    template: (n) => `${n}は雪を甘いと信じて食べ続け、内側から凍って動かなくなった。`,
  },
  spring_drunk: {
    id: 'spring_drunk',
    title: '春／泥水ビールで泥酔転倒',
    rare: false,
    points: 9,
    template: (n) => `${n}は花見のつもりで泥水ビールを一気飲みし、踊り出して即転倒した。`,
  },
  autumn_harvest: {
    id: 'autumn_harvest',
    title: '秋／棒会議農法で掘り出され',
    rare: false,
    points: 13,
    template: (n) => `${n}は収穫の最中、棒会議農法の一振りで根ごと掘り返された。`,
  },
  noukou_mud: {
    id: 'noukou_mud',
    title: '農業区の泥畑に埋もれ',
    rare: false,
    points: 11,
    template: (n) => `${n}は種を逆さに植えようとして自分が埋まった。`,
  },
  kouba_spark: {
    id: 'kouba_spark',
    title: '火花で発火',
    rare: false,
    points: 13,
    template: (n) => `${n}は作業場の小さな火花を見に行き、まもりんから燃え広がった。`,
  },
  taiko_crush: {
    id: 'taiko_crush',
    title: '足場の下敷き',
    rare: false,
    points: 14,
    template: (n) => `${n}は作業足場の真下を覗き込み、落ちてきた板で平たくなった。`,
  },
  cocoon_abuse: {
    id: 'cocoon_abuse',
    title: '棒つつき事故',
    rare: false,
    points: 15,
    template: (n) => `${n}は落ちていた棒を調べすぎ、周りに突かれ続けて動かなくなった。`,
  },

  // =========================================================================
  // Uncommon — 特性 × 状況ゲートで解禁される死因。通常プレイの後半で徐々に埋まる。
  // =========================================================================
  bouken_cliff: {
    id: 'bouken_cliff',
    title: '冒険家の墜落',
    rare: false,
    uncommon: true,
    points: 22,
    template: (n) => `${n}はまだ誰も渡っていない泥川の奥を覗こうとして戻って来なかった。`,
  },
  gourmand_choke: {
    id: 'gourmand_choke',
    title: '食いしん坊の詰まり',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}はどんぐりを三口で飲み込もうとして喉が鳴らなくなった。`,
  },
  shinpai_kashou: {
    id: 'shinpai_kashou',
    title: '心配性の過呼吸',
    rare: false,
    uncommon: true,
    points: 19,
    template: (n) => `${n}は遠くの足音を全部危険だと思い込み、息ができなくなって膝をついた。`,
  },
  ukiyo_shoushitsu: {
    id: 'ukiyo_shoushitsu',
    title: '浮世離れの消失',
    rare: false,
    uncommon: true,
    points: 24,
    template: (n) => `${n}は「わふ…とは…」と呟いてそのまま輪郭が薄くなっていった。`,
  },
  ikusa_taezetsu: {
    id: 'ikusa_taezetsu',
    title: '戦闘狂の相討ち',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は落ちていた棒を奪い合い、勝つ前に泥へ転がった。`,
  },
  noumin_umore: {
    id: 'noumin_umore',
    title: '農民気質の自埋め',
    rare: false,
    uncommon: true,
    points: 20,
    template: (n) => `${n}は収穫祭の一番乗りを目指して自分から畝に飛び込んだ。`,
  },
  suzu_kazoe_shikujiri: {
    id: 'suzu_kazoe_shikujiri',
    title: '点呼に数えられず',
    rare: false,
    uncommon: true,
    points: 17,
    template: (n) => `${n}は点呼が終わる前にどこかへ転がり、記録簿から名前だけが残った。`,
  },
  taiko_tobikomi: {
    id: 'taiko_tobikomi',
    title: '足場への飛び込み',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は作業足場の真ん中に飛び込むのが一番近道だと信じた。`,
  },

  // --- P6 ------
  morashi_fall: {
    id: 'morashi_fall',
    title: 'もらしで転倒→溺死',
    rare: false,
    uncommon: true,
    points: 19,
    template: (n) => `${n}はもらした水たまりで足を滑らせ、自分の痕跡に沈んだ。`,
  },
  oshaberi_choked: {
    id: 'oshaberi_choked',
    title: 'おしゃべりの息切れ',
    rare: false,
    uncommon: true,
    points: 21,
    template: (n) => `${n}は移動中もしゃべり続け、酸素を吸う順番を忘れて息絶えた。`,
  },
  tabikko_boundary: {
    id: 'tabikko_boundary',
    title: '旅っ子の境界越え',
    rare: false,
    uncommon: true,
    points: 23,
    template: (n) => `${n}は村のふちを越えようと踏み出し、誰にも見つからなくなった。`,
  },
  tetsugakusha_shoushitsu: {
    id: 'tetsugakusha_shoushitsu',
    title: '哲学者の自己消失',
    rare: false,
    uncommon: true,
    points: 30,
    template: (n) => `${n}は「自分とは何か」に答えが出た瞬間、跡形もなく消えた。`,
  },
  bo_meijin_tenka: {
    id: 'bo_meijin_tenka',
    title: '棒名人の返り討ち（他個体が犠牲）',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は棒名人の一閃を真横から受け、踊りながら退場した。`,
  },
  namaiki_boko: {
    id: 'namaiki_boko',
    title: '生意気を言ってボコボコ',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}はくそざこの分際で生意気を言い、周りから棒でボコボコにされた。`,
  },
  rifujin_boko: {
    id: 'rifujin_boko',
    title: '粗相で理不尽にボコられ死亡',
    rare: false,
    uncommon: true,
    points: 20,
    template: (n) => `${n}は屁やしゃっくりや涎など、何か些細な粗相をしただけでなぜか周りからボコボコにされて死んだ。`,
  },
  kamisama_punch: {
    id: 'kamisama_punch',
    title: '神様の鉄槌',
    rare: false,
    uncommon: true,
    points: 30,
    template: (n) => `${n}は空から落ちてきた神の手に撃ち抜かれ、ぺしゃんこになった。`,
  },
  kamisama_drown: {
    id: 'kamisama_drown',
    title: '神様に投げ込まれて水死',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は神様に掴まれ、ぽいっと泥川に投げ込まれ沈んだ。`,
  },
  kamisama_shake: {
    id: 'kamisama_shake',
    title: '神様に振り回されて衰弱死',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は神様に掴まれたまま延々と振り回され、目を回して動かなくなった。`,
  },
  kamisama_throw: {
    id: 'kamisama_throw',
    title: '神様に投げつけられて墜死',
    rare: false,
    uncommon: true,
    points: 27,
    template: (n) => `${n}は神様にぽーんと遠くへ投げ飛ばされ、地面に激突して動かなくなった。`,
  },
  mama_lost: {
    id: 'mama_lost',
    title: 'ママロス死（フラナ喪失）',
    rare: true,
    points: 40,
    template: (n) => `${n}はフラナママがいなくなった世界に耐えきれず、泣きながら動かなくなった。`,
  },
  hunger_death: {
    id: 'hunger_death',
    title: '餓死',
    rare: false,
    uncommon: true,
    points: 16,
    template: (n) => `${n}は食べ物が見つからず、お腹を鳴らしながら動かなくなった。`,
  },
  fatigue_death: {
    id: 'fatigue_death',
    title: '疲労死',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}はくたくたに疲れ果て、そのまま目を覚まさなかった。`,
  },
  flood_drown: {
    id: 'flood_drown',
    title: '洪水溺死',
    rare: false,
    uncommon: true,
    points: 22,
    template: (n) => `${n}は溢れた水路の流れに飲み込まれ、ぷかぷかと流れていった。`,
  },
  wolf_bite: {
    id: 'wolf_bite',
    title: 'オオカミに噛まれて',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は夜の闇から現れたオオカミに一噛みされ、まもりんだけが残った。`,
  },
  // --- Ω-6 電力 追加 ------------------------------------------------------
  electrocution: {
    id: 'electrocution',
    title: '感電死',
    rare: false,
    uncommon: true,
    points: 32,
    template: (n) => `${n}は光る電線を触り、ピカッと一瞬だけ明るくなって倒れた。`,
  },
  thunder_blast: {
    id: 'thunder_blast',
    title: '落雷直撃',
    rare: true,
    points: 48,
    template: (n) => `${n}はペダル発電所の屋根に落ちた雷をもろに受け、黒焦げになった。`,
  },

  // --- Σ-1 z物理 追加 -----------------------------------------------------------
  cliff_fall: {
    id: 'cliff_fall',
    title: '崖からの墜落',
    rare: false,
    uncommon: true,
    points: 24,
    template: (n) => `${n}は崖の端で「すべらないわふ」と自信満々に一歩踏み出し、次の瞬間には眼下の岩場に転がっていた。`,
  },
  slope_fall: {
    id: 'slope_fall',
    title: '坂道滑落死',
    rare: false,
    uncommon: true,
    points: 21,
    template: (n) => `${n}は急な坂道をドタドタ駆け下りて止まれず、谷底まで転がり続けた。`,
  },
  river_swept: {
    id: 'river_swept',
    title: '激流に飲み込まれ溺死',
    rare: false,
    uncommon: true,
    points: 23,
    template: (n) => `${n}は増水した水路で流されまいと必死にもがいたが、流れに逆らえずそのまま沈んだ。`,
  },
  // --- Σ-2-c 地形崩落 追加 --------------------------------------------------
  landslide_crush: {
    id: 'landslide_crush',
    title: '土砂崩れで圧死',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は「なんか地面がぐらぐらするわふ」と言った直後、土の塊に押し潰されて動かなくなった。`,
  },
  buried_alive: {
    id: 'buried_alive',
    title: '生き埋め窒息死',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は崩れてきた土の中から「むぐ……わ……ふ……」という声だけを残し、そのまま出てこなかった。`,
  },
  // --- Σ-5-d 狼 flee -------------------------------------------------------
  fled_to_exhaustion: {
    id: 'fled_to_exhaustion',
    title: '逃げ疲れ食われ死',
    rare: false,
    uncommon: true,
    points: 24,
    template: (n) => `${n}は「むり！もうむり！」と叫びながら全力で逃げたが、疲れ果てて道端に倒れ込み、追いかけてきたオオカミにそのまま食われた。`,
  },
  // --- Σ-7-d 水動力 --------------------------------------------------------
  drown_pond: {
    id: 'drown_pond',
    title: '水たまりで溺死',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}は雨水の溜まった水たまりに足を滑らせ、ぴちゃっとはまってそのまま沈んだ。`,
  },
  // M2.1: 飛んできた誰かに巻き込まれた巻き添え死。
  // 旧 cocoon_abuse の「飛行衝突」分岐をここへ移し替え（ココン廃止に伴う rename）。
  bystander_collision: {
    id: 'bystander_collision',
    title: '巻き込まれて衝突死',
    rare: false,
    points: 8,
    template: (n) => `${n}は飛んできた誰かに思いきり激突され、そのまま動かなくなった。`,
  },
  // M2.1: フラナの怒りパンチ/投げによる死亡。
  // 旧 cocoon_abuse の「フラナ暴力」分岐をここへ移し替え（ココン廃止に伴う rename）。
  furana_punch: {
    id: 'furana_punch',
    title: 'ママの怒りパンチで死亡',
    rare: false,
    points: 12,
    template: (n) => `${n}は機嫌の悪いママに本気で殴られ、そのまま動かなくなった。`,
  },
} as const;

export const DEATH_IDS = Object.keys(DEATH_CAUSES) as Array<keyof typeof DEATH_CAUSES>;
