import type { DeathCause } from '../types';

export const DEATH_CAUSES: Record<string, DeathCause> = {
  bokaigi: {
    id: 'bokaigi',
    title: '棒会議で極刑',
    rare: false,
    points: 12,
    template: (n) => `${n}は議題がわからないまま棒で殴られ続け倒れた。`,
  },
  ondo: {
    id: 'ondo',
    title: 'くそざこ音頭で転倒',
    rare: false,
    points: 8,
    template: (n) => `${n}は音頭の最中に前の個体の足に引っかかり転倒、動かなくなった。`,
  },
  mudriver: {
    id: 'mudriver',
    title: '泥川溺水',
    rare: false,
    points: 6,
    template: (n) => `${n}は泥川の光る何かに吸い寄せられ、静かに沈んだ。`,
  },
  stonebread: {
    id: 'stonebread',
    title: '石パンで歯折れ',
    rare: false,
    points: 7,
    template: (n) => `${n}は石パンに噛みつき、歯と意識を同時に失った。`,
  },
  bridge: {
    id: 'bridge',
    title: '丸太橋崩壊',
    rare: false,
    points: 9,
    template: (n) => `${n}が渡り始めた直後、橋は泥川へ帰っていった。`,
  },
  fire: {
    id: 'fire',
    title: '鍛冶場からの延焼',
    rare: false,
    points: 10,
    template: (n) => `${n}は火事の方向へ行き、火事の方向から戻って来なかった。`,
  },
  roushuai: {
    id: 'roushuai',
    title: '老衰（くそざこ寿命）',
    rare: false,
    points: 4,
    template: (n) => `${n}はまもりんを握りしめ、わふっと呟いて息絶えた。`,
  },
  philosophy: {
    id: 'philosophy',
    title: 'なぜわふ…で干からび',
    rare: true,
    points: 25,
    template: (n) => `${n}は「なぜわふ…」と立ち止まり、そのまま三日干からびた。`,
  },
  summer_boil: {
    id: 'summer_boil',
    title: '夏／沸騰池で煮え',
    rare: false,
    points: 14,
    template: (n) => `${n}は温泉と勘違いして沸騰寸前の泥水池に入り、そのまま出汁になった。`,
  },
  winter_snow: {
    id: 'winter_snow',
    title: '冬／雪を食べてそのまま',
    rare: false,
    points: 11,
    template: (n) => `${n}は雪を甘いと信じて食べ続け、内側から凍って動かなくなった。`,
  },
  spring_drunk: {
    id: 'spring_drunk',
    title: '春／泥水ビールで泥酔転倒',
    rare: false,
    points: 9,
    template: (n) => `${n}は花見のつもりで泥水ビールを一気飲みし、踊り出して即転倒した。`,
  },
  autumn_harvest: {
    id: 'autumn_harvest',
    title: '秋／棒会議農法で掘り出され',
    rare: false,
    points: 13,
    template: (n) => `${n}は収穫の最中、棒会議農法の一振りで根ごと掘り返された。`,
  },
  noukou_mud: {
    id: 'noukou_mud',
    title: '農業区の泥畑に埋もれ',
    rare: false,
    points: 11,
    template: (n) => `${n}は種を逆さに植えようとして自分が埋まった。`,
  },
  kouba_spark: {
    id: 'kouba_spark',
    title: '鍛冶場の火花で発火',
    rare: false,
    points: 13,
    template: (n) => `${n}は鍛冶場の火花に引火、まもりんから燃え尽きた。`,
  },
  taiko_crush: {
    id: 'taiko_crush',
    title: 'わふ太鼓やぐらで圧死',
    rare: false,
    points: 14,
    template: (n) => `${n}は太鼓の真下を覗き込み、次の一打で平たくなった。`,
  },
  cocoon_abuse: {
    id: 'cocoon_abuse',
    title: 'ココンのいじめで死亡',
    rare: false,
    points: 15,
    template: (n) => `${n}はココンに棒で突かれ続け、最後には動かなくなった。`,
  },

  // =========================================================================
  // Uncommon — 特性 × 状況ゲートで解禁される死因。通常プレイの後半で徐々に埋まる。
  // =========================================================================
  bouken_cliff: {
    id: 'bouken_cliff',
    title: '冒険家の墜落',
    rare: false,
    uncommon: true,
    points: 22,
    template: (n) => `${n}はまだ誰も渡っていない泥川の奥を覗こうとして戻って来なかった。`,
  },
  gourmand_choke: {
    id: 'gourmand_choke',
    title: '食いしん坊の詰まり',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}は石パンを三口で飲み込もうとして喉が鳴らなくなった。`,
  },
  shinpai_kashou: {
    id: 'shinpai_kashou',
    title: '心配性の過呼吸',
    rare: false,
    uncommon: true,
    points: 19,
    template: (n) => `${n}は音頭の足音で息ができなくなり、まもりんごと膝をついた。`,
  },
  ukiyo_shoushitsu: {
    id: 'ukiyo_shoushitsu',
    title: '浮世離れの消失',
    rare: false,
    uncommon: true,
    points: 24,
    template: (n) => `${n}は「わふ…とは…」と呟いてそのまま輪郭が薄くなっていった。`,
  },
  ikusa_taezetsu: {
    id: 'ikusa_taezetsu',
    title: '戦闘狂の相討ち',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}はココンの棒を奪おうとして、両方とも泥に転がった。`,
  },
  noumin_umore: {
    id: 'noumin_umore',
    title: '農民気質の自埋め',
    rare: false,
    uncommon: true,
    points: 20,
    template: (n) => `${n}は収穫祭の一番乗りを目指して自分から畝に飛び込んだ。`,
  },
  suzu_kazoe_shikujiri: {
    id: 'suzu_kazoe_shikujiri',
    title: 'スズの点呼に数えられず',
    rare: false,
    uncommon: true,
    points: 17,
    template: (n) => `${n}はスズが点呼を終える前に消え、記録簿から名前だけが残った。`,
  },
  taiko_tobikomi: {
    id: 'taiko_tobikomi',
    title: '祭りのやぐら飛び込み',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は太鼓の真ん中に飛び込むのが一番目立つと信じた。`,
  },

  // --- P6 ------
  morashi_fall: {
    id: 'morashi_fall',
    title: 'もらしで転倒→溺死',
    rare: false,
    uncommon: true,
    points: 19,
    template: (n) => `${n}はもらした水たまりで足を滑らせ、自分の痕跡に沈んだ。`,
  },
  oshaberi_choked: {
    id: 'oshaberi_choked',
    title: 'おしゃべりの息切れ',
    rare: false,
    uncommon: true,
    points: 21,
    template: (n) => `${n}は音頭中もしゃべり続け、酸素を忘れて息絶えた。`,
  },
  tabikko_boundary: {
    id: 'tabikko_boundary',
    title: '旅っ子の境界越え',
    rare: false,
    uncommon: true,
    points: 23,
    template: (n) => `${n}は村のふちを越えようと踏み出し、誰にも見つからなくなった。`,
  },
  tetsugakusha_shoushitsu: {
    id: 'tetsugakusha_shoushitsu',
    title: '哲学者の自己消失',
    rare: false,
    uncommon: true,
    points: 30,
    template: (n) => `${n}は「自分とは何か」に答えが出た瞬間、跡形もなく消えた。`,
  },
  bo_meijin_tenka: {
    id: 'bo_meijin_tenka',
    title: '棒名人の返り討ち（他個体が犠牲）',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は棒名人の一閃を真横から受け、踊りながら退場した。`,
  },
  namaiki_boko: {
    id: 'namaiki_boko',
    title: '生意気を言ってボコボコ',
    rare: false,
    uncommon: true,
    points: 18,
    template: (n) => `${n}はくそざこの分際で生意気を言い、周りから棒でボコボコにされた。`,
  },
  rifujin_boko: {
    id: 'rifujin_boko',
    title: '粗相で理不尽にボコられ死亡',
    rare: false,
    uncommon: true,
    points: 20,
    template: (n) => `${n}は屁やしゃっくりや涎など、何か些細な粗相をしただけでなぜか周りからボコボコにされて死んだ。`,
  },
  kamisama_punch: {
    id: 'kamisama_punch',
    title: '神様の鉄槌',
    rare: false,
    uncommon: true,
    points: 30,
    template: (n) => `${n}は空から落ちてきた神の手に撃ち抜かれ、ぺしゃんこになった。`,
  },
  kamisama_drown: {
    id: 'kamisama_drown',
    title: '神様に投げ込まれて水死',
    rare: false,
    uncommon: true,
    points: 28,
    template: (n) => `${n}は神様に掴まれ、ぽいっと泥川に投げ込まれ沈んだ。`,
  },
  kamisama_shake: {
    id: 'kamisama_shake',
    title: '神様に振り回されて衰弱死',
    rare: false,
    uncommon: true,
    points: 26,
    template: (n) => `${n}は神様に掴まれたまま延々と振り回され、目を回して動かなくなった。`,
  },
  kamisama_throw: {
    id: 'kamisama_throw',
    title: '神様に投げつけられて墜死',
    rare: false,
    uncommon: true,
    points: 27,
    template: (n) => `${n}は神様にぽーんと遠くへ投げ飛ばされ、地面に激突して動かなくなった。`,
  },
  mama_lost: {
    id: 'mama_lost',
    title: 'ママロス死（フラナ喪失）',
    rare: true,
    points: 40,
    template: (n) => `${n}はフラナママがいなくなった世界に耐えきれず、泣きながら動かなくなった。`,
  },
} as const;

export const DEATH_IDS = Object.keys(DEATH_CAUSES) as Array<keyof typeof DEATH_CAUSES>;
